services:
  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: frontend-service
    environment:
      PORT: 8081
      BACKEND_URL: http://${BACKEND_HOST}:8080
    ports:
      - "8081:8081"
