services:
  db:
    image: ${DB_IMAGE}
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: posts
    ports:
      - "5432:5432"
